### ISSUE TITLE
Readme example doesn't work: Link isn't correctly transformed

### ISSUE THREAD

**Issue by super-cache-money** [jsarafajr/slackify-markdown#1]
Using the latest version on npm, with this markdown: 
```
[here is an example](https://example.com)
```

I get this:
```
https://example.com
```

But I was hoping (as per the readme), to get this:
```
<https://example.com|here is an example>
```

**Comment by super-cache-money** [comment]
BTW, shoutout for making this! I was really glad it existed when I found it.

**Comment by jsarafajr** [comment]
Hi @super-cache-money. Could you please share a code sample? 
I've just tried the same exact input and seems it works as expected:
```
slackifyMarkdown('[here is an example](https://example.com)') -> '<https://example.com|here is an example>\n'
```
Here is the shared runkit script https://runkit.com/embed/k2y34zkpsw28

**Comment by super-cache-money** [comment]
My REPL with node 6.8.1, and slackify-markdown 1.0.4.
 
```
> const slackifyMarkdown = require('slackify-markdown');
undefined
> slackifyMarkdown('[here is an example](https://example.com)')
'https://example.com\n'
>
```

**Comment by super-cache-money** [comment]
Mysterious....

**Comment by super-cache-money** [comment]
npm test output:

```
jest

 FAIL  __test__/slackify-markdown.test.js
  ✓ Simple text (25ms)
  ✓ Escaped text (3ms)
  ✓ Headings (4ms)
  ✓ Bold (2ms)
  ✓ Bold character in word (2ms)
  ✓ Italic (2ms)
  ✓ Bold+Italic (2ms)
  ✓ Strike (1ms)
  ✓ Unordered list (4ms)
  ✓ Ordered list (2ms)
  ✕ Link (20ms)
  ✕ Link with title (4ms)
  ✓ Invalid link (2ms)
  ✕ Image (2ms)
  ✕ Image with alt-title (4ms)
  ✓ Image with invalid link (3ms)
  ✓ Inline code (2ms)
  ✓ Code block (3ms)
  ✓ Code block with language (1ms)
  ✓ Code block with deprecated language declaration (1ms)
  ✓ Emoji replace (2ms)

  ● Link

    expect(received).toBe(expected) // Object.is equality

    Expected value to be:
      "<http://atlassian.com|http://atlassian.com>
    "
    Received:
      "http://atlassian.com
    "

    Difference:

    - Expected
    + Received

    - <http://atlassian.com|http://atlassian.com>
    + http://atlassian.com


      60 |   const mrkdown = '[http://atlassian.com](http://atlassian.com)';
      61 |   const slack = '<http://atlassian.com|http://atlassian.com>\n';
    > 62 |   expect(slackifyMarkdown(mrkdown)).toBe(slack);
      63 | });
      64 |
      65 | test('Link with title', () => {

      at Object.toBe (__test__/slackify-markdown.test.js:62:37)

  ● Link with title

    expect(received).toBe(expected) // Object.is equality

    Expected value to be:
      "<http://atlassian.com|test>
    "
    Received:
      "http://atlassian.com
    "

    Difference:

    - Expected
    + Received

    - <http://atlassian.com|test>
    + http://atlassian.com


      66 |   const mrkdown = '[test](http://atlassian.com)';
      67 |   const slack = '<http://atlassian.com|test>\n';
    > 68 |   expect(slackifyMarkdown(mrkdown)).toBe(slack);
      69 | });
      70 |
      71 | test('Invalid link', () => {

      at Object.toBe (__test__/slackify-markdown.test.js:68:37)

  ● Image

    expect(received).toBe(expected) // Object.is equality

    Expected value to be:
      "<https://bitbucket.org/repo/123/images/logo.png|logo.png>
    "
    Received:
      "https://bitbucket.org/repo/123/images/logo.png
    "

    Difference:

    - Expected
    + Received

    - <https://bitbucket.org/repo/123/images/logo.png|logo.png>
    + https://bitbucket.org/repo/123/images/logo.png


      78 |   const mrkdown = '![logo.png](https://bitbucket.org/repo/123/images/logo.png)';
      79 |   const slack = '<https://bitbucket.org/repo/123/images/logo.png|logo.png>\n';
    > 80 |   expect(slackifyMarkdown(mrkdown)).toBe(slack);
      81 | });
      82 |
      83 | test('Image with alt-title', () => {

      at Object.toBe (__test__/slackify-markdown.test.js:80:37)

  ● Image with alt-title

    expect(received).toBe(expected) // Object.is equality

    Expected value to be:
      "<https://bitbucket.org/repo/123/images/logo.png|test>
    "
    Received:
      "https://bitbucket.org/repo/123/images/logo.png
    "

    Difference:

    - Expected
    + Received

    - <https://bitbucket.org/repo/123/images/logo.png|test>
    + https://bitbucket.org/repo/123/images/logo.png


      84 |   const mrkdown = "![logo.png](https://bitbucket.org/repo/123/images/logo.png 'test')";
      85 |   const slack = '<https://bitbucket.org/repo/123/images/logo.png|test>\n';
    > 86 |   expect(slackifyMarkdown(mrkdown)).toBe(slack);
      87 | });
      88 |
      89 | test('Image with invalid link', () => {

      at Object.toBe (__test__/slackify-markdown.test.js:86:37)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 17 passed, 21 total
Snapshots:   0 total
Time:        3.865s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by jsarafajr** [comment]
Oh, I see. The problem is node v6. 
I will try to fix.
